import type { Metadata } from "next"
import { Inter } from "next/font/google"

import Layout from "@/component/Layout/Layout"
import "./globals.css"
import { Providers } from "@/redux/provider"

const inter = Inter({ subsets: ["greek"] })

export const metadata: Metadata = {
  title: "FMIL",
  description: "Generated by FMIL",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          <Layout>{children}</Layout>
        </body>
      </html>
    </Providers>
  )
}
